### ISSUE TITLE
Eliminate settings table

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/StreamingLiveApi#7]
Now that appearance and subdomain are coming from accessApi, the settings table can go away.  Make sure all calls to it in the Web and App project are also removed.

**Comment by pranavmalvawala** [comment]
I've crossed verified it again. Table and its controller, repository does not exist anymore. I took them out few days back in this https://github.com/LiveChurchSolutions/StreamingLiveApi/pull/8 PR
